### ISSUE TITLE
[bug]: responding 500 code even though it's not defined in resolver or response

### ISSUE THREAD

**Issue by PyaePhyoKyaw61194** [mm-ninja-turtles/turtle-express#43]
<img width="1454" alt="Screenshot 2022-08-19 at 07 39 38" src="https://user-images.githubusercontent.com/36658378/185507524-5e67bb9d-11a5-41b0-8dba-0a824cc544c5.png">

I tested the example code and it did not return 400. Instead, the response is 500 and 200 at a random situation.

**Comment by wai-lin** [comment]
It seems to be validation error is taking over the actual 400 response. It's an internal bug after changing the internally to the lifecycle.

**Comment by PyaePhyoKyaw61194** [comment]
After checking for source code , I found that **_context.resolverValidation.error_**  from safeParse always returns undefined. 
![Screenshot 2022-08-20 at 22 21 22](https://user-images.githubusercontent.com/36658378/185748143-fe8a3d1b-40d8-48ff-a052-b5b742350a20.png)

**Comment by PyaePhyoKyaw61194** [comment]
As a temporary fix , I suggest to set **_error_** property of the **_context.responseInit_** as **_null_**
![Screenshot 2022-08-20 at 22 25 32](https://user-images.githubusercontent.com/36658378/185748327-929af433-8a5c-4391-b6cc-519bdfc63207.png)

**Comment by PyaePhyoKyaw61194** [comment]
@wai-lin

**Comment by PyaePhyoKyaw61194** [comment]
Since the error is undefined.,the format() method won't work.

**Comment by wai-lin** [comment]
@PyaePhyoKyaw61194

this should be solved in `v0.1.5`. Let me know if you're still experiencing this.
