### ISSUE TITLE
[feature]: Typescript cannot detect the undefined properties of (params,body,query of ctx) 

### ISSUE THREAD

**Issue by PyaePhyoKyaw61194** [mm-ninja-turtles/turtle-express#44]
<img width="1460" alt="Screenshot 2022-08-20 at 00 46 23" src="https://user-images.githubusercontent.com/36658378/185657494-ed8b48a2-4a5d-46c1-afbe-1af77b81a153.png">

Typescript cannot detect the **name** property that is not existed.

**Comment by PyaePhyoKyaw61194** [comment]
I just added the query object in request without any property. In this case, typescript can detect the undefined error( **name** not existed in query) perfectly.
<img width="837" alt="Screenshot 2022-08-20 at 00 54 43" src="https://user-images.githubusercontent.com/36658378/185659036-eb9c0050-2b47-4830-a4d9-394eeeedda79.png">

**Comment by wai-lin** [comment]
This might be the case that I need to type the defaults of context elements to `unknown` so that typescript can show error correctly. I'll need to investigate more.

**Comment by PyaePhyoKyaw61194** [comment]
Trying to copy the logic of ResolverArgs return type changing dynamically( **_ctx,req,res_** or **_ctx,req_**) with respect to UncontrolledResolver true or false. But , still failed.

**Comment by wai-lin** [comment]
Yep it would still be the same result since `ResolverArgs` need to type more strictly.

**Comment by wai-lin** [comment]
#55

**Comment by wai-lin** [comment]
This should be solved. I'll close the issue.
