### ISSUE TITLE
[feature]: possible duplicate name conflicts in ctx(context) object of resolver

### ISSUE THREAD

**Issue by PyaePhyoKyaw61194** [mm-ninja-turtles/turtle-express#45]
<img width="1269" alt="Screenshot 2022-08-20 at 02 50 38" src="https://user-images.githubusercontent.com/36658378/185678205-feea6912-58c2-40da-a64c-368036d4662f.png">

We should keep reserved names ( params, body , query ... ? ) for property name of custom context to avoid conflicts.

**Comment by wai-lin** [comment]
ah yes, we should reserve those names. I don't know how to reserve it yet though. 🤣

**Comment by wai-lin** [comment]
I'll close this issue since `v0.2.0` removed the context for the duplicate names and the problem of where the context value came from when we introduce root level context for plugin api.
