### ISSUE TITLE
[docs]: new resources for documentation

### ISSUE THREAD

**Issue by PyaePhyoKyaw61194** [mm-ninja-turtles/turtle-express#46]
About the documentation( Github wiki for now), I will add 
**03**. router
**04**.path
**04**.handler
 of the framework.

**Comment by wai-lin** [comment]
I'm thinking of using [astro](https://astro.build) for creating documentation website in the future.

**Comment by PyaePhyoKyaw61194** [comment]
Got it , let me add in wiki first

**Comment by wai-lin** [comment]
this is the duplicate of #23.
