### ISSUE TITLE
[feature]: typescript not working well with zod array validation

### ISSUE THREAD

**Issue by PyaePhyoKyaw61194** [mm-ninja-turtles/turtle-express#52]
I have to use zod array validation to return users. In this case, typescript cannot show error for resolver.
<img width="1134" alt="Screenshot 2022-08-21 at 03 52 41" src="https://user-images.githubusercontent.com/36658378/185762276-17ce7d45-b384-4ffe-b2ff-b29a217abc82.png">

**Comment by PyaePhyoKyaw61194** [comment]
As for comparison , I added the simple object validation for 400 message. In this case, typescript works
<img width="1134" alt="Screenshot 2022-08-21 at 03 53 41" src="https://user-images.githubusercontent.com/36658378/185762325-c238acf2-7744-4f08-9f0c-0602b5c7682f.png">

**Comment by PyaePhyoKyaw61194** [comment]
Even though the typescript does not work well., our lib can still detect the error in run time. The validation error is caught when the **_name_** property is not included in resolver return type.

**Comment by wai-lin** [comment]
#55

**Comment by wai-lin** [comment]
@PyaePhyoKyaw61194 this should be solved since `v0.2.0` is this solved for you?

**Comment by PyaePhyoKyaw61194** [comment]
@wai-lin yep, we can close this.
