### ISSUE TITLE
[bug]: in request validation

### ISSUE THREAD

**Issue by PyaePhyoKyaw61194** [mm-ninja-turtles/turtle-express#57]
I tested this kind of example with request body

```
const users = router.path('/users')

users.handler({
	id: 'CreateNewUser',
	method: 'post',
	request: {
		body: z.object({
			name: z.string().min(1, { message: 'name is required.' }),
			email: z.string().email({ message: 'wrong email format.' }),
		}),
	},
	response: {
		200: z.object({
			name: z.string(),
			email: z.string().email(),
		}),
	},
	async resolver({ ctx }) {
		const { name, email } = ctx.body
		const user = await db.users.create({ name, email })
		return {
			200: user,
		}
	},
})
'''

**Comment by PyaePhyoKyaw61194** [comment]
I got 500 internal server error even though I put the name and email for body.

The Response 
```
{
  "success": false,
  "message": "Something went wrong!",
  "data": null,
  "error": "[case `resolver`]: Invalid state"
}
```

The Request Body (tested in Thunder Client)
```
{
 "name": "Mg Mg",
 "email" : "mgmg@gmail.com"
}
```

**Comment by PyaePhyoKyaw61194** [comment]
Another test is , I added query validation( with body validation ) this time. 
```
request: {
		query: z.object({
			limit: z.string(),
		}),
	},
```
I got the same error response if the zod validation is failed. (I did not add limit query string)
```
{
  "success": false,
  "message": "Something went wrong!",
  "data": null,
  "error": "[case `resolver`]: Invalid state"
}
```

Last time I checked , I think the error message is a bit more explicit zod error message like "limit is required " (same meaning like this).

**Comment by PyaePhyoKyaw61194** [comment]
@mm-ninja-turtles/core-maintainers

**Comment by PyaePhyoKyaw61194** [comment]
@wai-lin  I found that req.body will get undefined in requestValidation method.

**Comment by PyaePhyoKyaw61194** [comment]
@wai-lin  The problem is solved by adding **_router.use(express.json()_**) before **_router.setup({})_**

**Comment by wai-lin** [comment]
@PyaePhyoKyaw61194

I've updated the getting started guide. please read and do as it is.

From `v0.2.0`, setup function only the route setup of paths. No more extra works. Which mean it doesn't enable `express.json()` or `express.urlencoded()` by default. Giving the user the full control of the app setup.

If this is resolved as you've said, I'll close this issue.
