### ISSUE TITLE
[bug] : zod validation error explanation

### ISSUE THREAD

**Issue by PyaePhyoKyaw61194** [mm-ninja-turtles/turtle-express#59]
I put the request validation like this.

```
request: {
		query: z.object({
			limit: z.string(),
		}),
	},
```

and I didn't add the required **_limit_** query string in my api call.

I got this error response.

```
{
  "success": false,
  "message": "Something went wrong!",
  "data": null,
  "error": "[case `resolver`]: Invalid state"
}

```
with 500 HTTP status code.

Is it better if we can get the real zod error message? ( **_limit_** is required .. some meaning like that )

**Comment by wai-lin** [comment]
This is a bug inside handler function. It should show validation error. I'll check on it.

**Comment by wai-lin** [comment]
resolver function lifecycle state: 2 found was found with a bug. request schema validation state is not handling the next state properly. By fixing the next state handling logic, this should be fixed.
